CREATE TABLE worker (
    worker_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50) NOT NULL,
    sur_name      VARCHAR2(50) NOT NULL,
    department     VARCHAR2(50),
    salary         NUMBER(10,2),
    join_date      DATE DEFAULT SYSDATE
);
